### ISSUE TITLE
Crash in sdk 3.1.1 during migration from 2.x

### ISSUE THREAD

**Issue by khurram18** [customerio/customerio-ios#703] opened 2024-04-16 06:30 UTC
**SDK version:** 3.1.1

**Environment:** Production

**Are logs available?** 
Please see attached screen shot
                            
**Describe the bug**
We followed the SDK migration guide from 2.x to 3.x here https://customer.io/docs/sdk/ios/whats-new/3.x-upgrade/#_

**To Reproduce**
Just update to SDK from 2.x to 3.x and run the app.

**Expected behavior**
SDK should initialize and work without any crashes.

**Screenshots**
See attached
<img width="2429" alt="Screenshot 2024-04-16 at 11 18 28 AM" src="https://github.com/customerio/customerio-ios/assets/7508106/b8714ed8-3220-4044-8778-2c930a9c97ee">

**Additional context**
From screenshot it is clear that a force unwrap of optional variable `attributesJsonString` of `trackTaskData` is accessed.

**Comment by mrehan27** [comment] 2024-04-16 08:47
Hey @khurram18, apologies for the issue you're experiencing. I believe this is the same as reported in issue #698. We have identified the root cause and are actively working on the fix, which will be rolled out very soon once we complete testing.

I'm closing this as duplicate of #698 so we can keep all related discussions in one place. Meanwhile, if you have more details that could help us validate the fix, please feel free to share them.

Sorry again for the inconvenience it may have caused. I can assure you that the fix will be rolled out very soon. We appreciate your patience.

Thank you for reaching out and sharing great details. Although this issue is closed, please don't hesitate to ask any further questions or share additional feedback.

**Closed by mrehan27** 2024-04-16 08:47 UTC

**Comment by levibostian** [comment] 2024-04-16 17:17
Version `3.1.2` of the Customer.io iOS SDK has been deployed and ready to install. This release includes a bug fix to resolve this crash. 

Thank you again for reporting this to us and working with us to get it resolved. Sorry that you experienced this crash. We hope `3.1.2` is successful for you. If not, please reach out again.

**Comment by khurram18** [comment] 2024-04-17 03:50
Thank you @mrehan27 and @levibostian the new version worked without any issues.
