### ISSUE TITLE
Original Segment integration is broken by CustomerIO

### ISSUE THREAD

**Issue by alexandervybz** [customerio/customerio-ios#705] opened 2024-04-18 09:10 UTC
**SDK version:** 3.1.0

**Describe the bug**
This line `.package(name: "Segment", url: "https://github.com/customerio/cdp-analytics-swift.git", .exact("1.5.9"))` is breaking my original Segment integration with the error:

`multiple similar targets 'Segment' appear in package 'analytics-swift' and 'cdp-analytics-swift', this may indicate that the two packages are the same and can be de-duplicated by using mirrors. if they are not duplicate consider using the `moduleAliases` parameter in manifest to provide unique names`

Module alias and mirror url don't help:
```
{
  "object" : [
    {
      "mirror" : "https://github.com/segmentio/analytics-swift.git",
      "original" : "https://github.com/customerio/cdp-analytics-swift.git"
    }
  ],
  "version" : 1
}
```

**To Reproduce**
Add packages:
```
.package(
    url: "https://github.com/segmentio/analytics-swift.git",
    from: "1.5.9"
),
.package(
    url: "https://github.com/segment-integrations/analytics-swift-appsflyer.git",
    from: "1.1.8"
),
```
and
```
.package(
    url: "https://github.com/alexandervybz/customerio-ios.git",
    branch: "main"
)
```

**Expected behavior**
Either alias created inside CustomerIO, Segment is optional only for case when it's needed, or it uses original Segment SDK.

**Comment by mrehan27** [comment] 2024-04-18 11:44
Hey @alexandervybz, thank you for your feedback and providing such detailed information. I see you're running both Customer.io SDK and the analytics-swift SDK in your app. As [being discussed in earlier issue](https://github.com/customerio/customerio-ios/issues/670), we are currently evaluating the effort required to support both SDKs running in parallel, but we haven't finalized a solution yet.

In the meantime, you can [continue using V2](https://github.com/customerio/customerio-ios/releases/tag/2.13.0), as it is fully supported and compatible with analytics-swift SDK. I'm closing this since we have an internal ticket to track this issue, and we will keep you updated on any developments. If you have any additional feedback or more use cases to share regarding the integration of analytics-swift SDK with V3, please do share with us. If it's easier to share privately you can email [product@customer.io](mailto:product@customer.io) to start a thread with our product team.

Even though the issue is closed, please don't hesitate to continue asking questions or sharing any further feedback you may have. Thanks again. Have a great day.

**Closed by mrehan27** 2024-04-18 11:44 UTC

**Comment by Ahmed-Ali** [comment] 2024-05-07 18:05
Hi @alexandervybz, just circling back real quick on this in case you missed it. We priortizing this issue and from the release 3.2 this issue should be solved.
