### ISSUE TITLE
Memory/CPU Hang in 2.0.2

### ISSUE THREAD

**Issue by janremes** [customerio/customerio-ios#248] opened 2023-01-10 13:42 UTC
**SDK version:** 2.0.2

**Environment:**  Production

**Are logs available?** 
In logs I see just theese

```
[CIO] (siteid:6cbe9) ℹ️ Customer.io SDK 2.0.2 initialized and ready to use for site id: xxx
[CIO] (siteid:6cbe9) ℹ️ registering device token xxx
[CIO] (siteid:6cbe9) ℹ️ adding queue task registerPushToken
[CIO] (siteid:6cbe9) ℹ️ queue met criteria to run automatically
```

**Describe the bug**
SDK is taking all available memory and CPU resources in version 2.0.2. App is then unusable. This is not happening in 2.0.1

**To Reproduce**
For me is enough just to launch app on device. In stack trace it seems to be failing when trying to update push token with customer.io

Here is stack trace I see on client.
<img width="791" alt="Screenshot 2023-01-10 at 14 35 42" src="https://user-images.githubusercontent.com/1276036/211565979-600ff9a7-7be0-4760-816d-d0cf4bf2f0a7.png">

**Comment by levibostian** [comment] 2023-01-10 20:57
Thanks for reporting this to us, @janremes. 

Sorry that you're experiencing a problem. We have this issue noted and am trying to reproduce it on our end. We'll get back to you with updates or questions when we have them. 

I am curious, how did you capture the stack trace and SDK logs that you attached? Are you running the app locally for testing purposes? If so, [can you enable debug logs for us to get more log messages and send those to us](https://github.com/customerio/customerio-ios/blob/develop/docs/SUPPORT.md#how-to-capture-logs-from-sdk-to-send-to-customerio-team)? 

In the mean time, I hope that version 2.0.1 will work for you!

**Comment by janremes** [comment] 2023-01-11 11:54
Yes I'm running app locally on a device. Logs via console are the same I attached before: 

[logs.txt](https://github.com/customerio/customerio-ios/files/10391988/logs.txt)

A few seconds after start, customer.io sdk will take all available memory and CPU. I can try to isolate it into small xcodeproject, it seems to be related to updating push token.

**Comment by levibostian** [comment] 2023-01-11 14:25
Thanks for including the logs. 

[If you enable the `debug` log level](https://github.com/customerio/customerio-ios/blob/develop/docs/SUPPORT.md#how-to-capture-logs-from-sdk-to-send-to-customerio-team) instead of the default, I believe you should see more logs in the console then you are seeing right now. 

If you get a chance, seeing the debug logs would be useful. I have a couple ideas for why this behavior could be happening and seeing those logs could help guide me in reproducing.

**Comment by levibostian** [comment] 2023-01-11 14:53
@janremes I am able to reproduce the issue. No need to send debug logs to me. 

I'm looking into the issue and will update you along the way. 

Again, sorry for the issues you have been experiencing.

**Comment by levibostian** [comment] 2023-01-18 14:49
@janremes 2.0.4 has been deployed that addresses this issue. 

Install it when you can and see if your issue has been resolved. 

Thanks again for all the information that you provided to help us find this! 

I'll close this for now since a bug fix has been deployed. Contact us again if you discover a new issue with 2.0.4

**Closed by levibostian** 2023-01-18 14:49 UTC
