### ISSUE TITLE
Can't find MessagingPush in scope

### ISSUE THREAD

**Issue by benjalimm** [customerio/customerio-ios#132] opened 2022-01-27 23:12 UTC
![image](https://user-images.githubusercontent.com/19392233/151458179-5ea58166-aa61-48df-9bd7-596c45e85232.png)

Followed instructions to get Firebase messaging integration working. Here are the imports:
![image](https://user-images.githubusercontent.com/19392233/151458630-123a083c-0454-491d-aca6-77f1cfcf3416.png)

Also, the imports are clearly working because I can call identify. 

Any idea how to solve this?

**Comment by levibostian** [comment] 2022-01-28 14:15
Hey there, @benjalimm 👋

I have experienced this in the past as well. Add this import to your file:
```swift
import CioMessagingPush
```

I just created a new Xcode iOS project to try and reproduce your issue and I was able to resolve it with that import. 

Thanks for point this out. I have submitted an update to our [FCM documentation](https://customer.io/docs/sdk/ios/push/#push-with-fcm) to add this missing import in the setup code. 

Give that a shot.

**Comment by levibostian** [comment] 2022-02-02 16:25
I'll close this issue as I'm assuming it's resolved. Feel free to comment on it if the issue is not resolved. 

The public docs website has been updated to add this missing `import` statement.

**Closed by levibostian** 2022-02-02 16:25 UTC

**Comment by ninjz** [comment] 2022-11-08 02:53
Would be good to update the docs with an objective-c example; I can't seem to integrate with FCM on iOS following the current instructions.

**Comment by kalitk0** [comment] 2023-07-02 10:08
> Would be good to update the docs with an objective-c example; I can't seem to integrate with FCM on iOS following the current instructions.

Have you found a solution ?
