### ISSUE TITLE
Won't compile when installed via CocoaPods and using Notification Extension.

### ISSUE THREAD

**Issue by ddanielczyk** [customerio/customerio-ios#178] opened 2022-07-15 08:14 UTC
Hi,

When I add a Notification Service Extension to handle Rich Pushes, I need to include there `CioMessagingPushAPN` pod.

The problem is, it won't compile, since there is a code in SDK that is not available to App Extensions in general.

As an example, `UIApplication.shared` is not available in extensions. Probably these methods that are not needed from within extension, should be marked with `@available(iOSApplicationExtension, unavailable)`.

![Zrzut ekranu 2022-07-15 o 10 10 52](https://user-images.githubusercontent.com/939650/179182260-d8af7123-fbbf-47ce-9145-560337c940f4.png)

When SDK is installed via SPM - it works fine.

Could you please check and fix this, so that it's possible to use the SDK via CocoaPods ? Thank you!

**Comment by levibostian** [comment] 2022-07-15 13:41
Hey there, @ddanielczyk. Thanks for asking this question. 

I have recently experienced this myself actually. I have a couple of solutions for you. 

1. I have created a branch with a potential bug fix to address this problem. Branch name is `levi/compile-notification-service`. If you could, install that branch from your `Podfile` and see if that fixes the compilation issue you're having. I have not been able to test this branch very well yet so having you try it would be very helpful. 

I don't recommend using the branch in production as we have not QA tested all the commits inside of that branch yet. So, I do have this recommendation as a workaround to get your app moving closer to production:
2. At the end of your `Podfile`, insert this code:
```ruby
cio_target_names = [
  'CustomerIOTracking',
  'CustomerIOMessagingPushAPN',
  'CustomerIOMessagingPush'
]

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if cio_target_names.include? target.name
      puts "Modifying target #{target.name}"

      target.build_configurations.each do |config|
        puts "Setting build config settings for #{target.name}"
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] ||= 'NO'
      end
    end
  end
end
```

This code's job is to disable this compiler warning that's being done for the application extension just for the Customer.IO SDK targets.

**Comment by ddanielczyk** [comment] 2022-07-15 19:23
Hi @levibostian , Thank you.

So solution 1 does not seem to work, is this maybe that .podspec file on this branch is not up to date? Possibly it's missing the Common module. I couldn't get it to compile.

Solution 2 works, as a temporary solution that's fine, but xCode now shows warnings that it's not safe, and I wouldn't go to production with it.

Solution 1 seems to be a way to go, but it's not complete. Looks like file structure has changed between Main and Develop quite a lot and it's probably not updated in spec.

Thanks again

**Comment by levibostian** [comment] 2022-07-15 19:38
For solution 1, is this what you're using in your `Podfile`? 

```ruby
  pod 'CustomerIO/Tracking', :git => "https://github.com/customerio/customerio-ios.git", :branch => 'levi/compile-notification-service'
  pod 'CustomerIO/MessagingPushAPN', :git => "https://github.com/customerio/customerio-ios.git", :branch => 'levi/compile-notification-service' # '~> 1.1'
```

---

I should also note that you can use SPM and cocoapods at the same time in the same project. Some dependencies installed with SPM and some with cocoapods. 

You could install all of the Customer.io SDKs with SPM and your others with cocoapods.

**Comment by ddanielczyk** [comment] 2022-07-15 20:27
Yes, thats exactly what I used. I still believe that since even on this branch the .podspec file source property leads to tag: 1.1.1 -> it downloads actually code from this tag, which is from Main and does not contain the Common directory/module at all. (Altough I may be wrong ;)) )

I am aware about SPM solution and thats the way how I got it working. Still, since we use cocoapods across the project and it seems to be supported by customer.io - that would be the preferred way - if possible. Otherwise, we will probably stick to SPM for customer.io lib.

Thanks

**Comment by ddanielczyk** [comment] 2022-07-15 21:49
Ok, we are heading in good direction. I can see new file structure now, together with the changes on compile-notification-service branch. But - it still won't compile as the Common directory and module is missing.

![Zrzut ekranu 2022-07-15 o 23 48 52](https://user-images.githubusercontent.com/939650/179315627-fe70062c-3ff0-4bfc-8d49-7db5b0152580.png)

**Comment by levibostian** [comment] 2022-07-18 14:48
Ah! Yes. That is a bug. 

Our current sample app that we maintain uses SPM so bugs like this are harder to catch. I appreciate you finding it and reporting it to me. 

I have made a fix to this compiling issue and pushed the change to `levi/compile-notification-service`. You should be able to pod update and try again.

**Comment by levibostian** [comment] 2022-07-19 18:36
Update on the bug fix branch `levi/compile-notification-service`, I have not been able to get a sample app compiling successfully using it. 

It seems like we will be recommending [solution 2](https://github.com/customerio/customerio-ios/issues/178#issuecomment-1185558583) in the `Podfile` for the time being until we can create a better solution. After working on this for a bit, it seems like there is more work then previously thought in regards to `@available(iOSApplicationExtension, unavailable)` in the project.

**Comment by levibostian** [comment] 2022-07-19 20:26
Update: I was able to implement a bug fix for this issue today. [Open PR](https://github.com/customerio/customerio-ios/pull/185) for it.

**Comment by ddanielczyk** [comment] 2022-07-20 07:48
Thank you!

**Comment by levibostian** [comment] 2022-07-26 21:21
Update: [Bug fix has been deployed in the latest Alpha release of the SDK](https://github.com/customerio/customerio-ios/pull/185#issuecomment-1195981877). The release is in Alpha so you may not feel comfortable using it in production, but you can feel free to [test that the bug fix works](https://github.com/customerio/customerio-ios/pull/185#issuecomment-1195995376) before we push the SDK to Beta!

**Closed by levibostian** 2022-07-26 21:21 UTC

**Comment by honcharenko13** [comment] 2023-11-21 16:23
<img width="1166" alt="Screenshot 2023-11-21 at 18 22 13" src="https://github.com/customerio/customerio-ios/assets/19774907/eaaf909d-8276-4001-b0f3-68ed9491f848">

hey @levibostian . It seems the same issue in CustomerIOMessagingInApp pod.

**Comment by levibostian** [comment] 2023-11-21 17:38
Sorry you are having an issue, @honcharenko13. 

I am guessing that you are experiencing this because your Notification Service Extension target includes the Customer.io in-app SDK as a dependency. 

Here is a `Podfile` from our [sample app](https://github.com/customerio/customerio-ios/blob/a2ccebf1dae6d891c8c699005a083a4147241130/Apps/CocoaPods-FCM/Podfile#L26-L31) that you can reference to see if it helps you. Notice how the in-app module is not included as a dependency in the NSE target.

**Comment by honcharenko13** [comment] 2023-11-21 18:44
<img width="1196" alt="Screenshot 2023-11-21 at 20 43 45" src="https://github.com/customerio/customerio-ios/assets/19774907/76c8aa52-354e-47f5-af62-7a3e9dd78c04">

Thanks for tips!

**Comment by levibostian** [comment] 2023-11-21 20:46
Thank you for pointing that out to us, @honcharenko13. 

I will share your latest comment with the team as that may be an issue on our end. Thank you for bringing this to our attention. Greatly appreciate it! I'll touch base soon with an update.

**Comment by levibostian** [comment] 2023-11-22 16:35
@honcharenko13, we have been able to reproduce the same issue [that you sent us](https://github.com/customerio/customerio-ios/issues/178#issuecomment-1821464983). A fix has been created and is currently being reviewed by the team. The fix will go to production as soon as review is concluded. 

Note: There may be a delay in getting this review completed because of some team members being out of the office for global holidays this week. We appreciate the patience.

**Comment by levibostian** [comment] 2023-11-22 19:46
iOS SDK version 2.10.1 has been deployed fixing this issue. Thanks again for reporting this to us and sorry for you encountering this. 

Enjoy!

**Comment by honcharenko13** [comment] 2023-11-27 15:24
@levibostian thank you guys for quick fix!
